import Head from "next/head"
import Link from "next/link"
import { useState } from "react"
import RpmFrame from "@/src/components/iframe"
import { get, useForm } from "react-hook-form"
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"

export default function Avator() {
  const {
    register,
    handleSubmit,
    getValues,
    watch,
    reset,
    formState: { errors },
    control,
  } = useForm()
  // useRouter
  const [rpmFrame, setRpmFrame] = useState(false)

  const handleInputChange = (event) => {
    setFormData({
      ...formData,
      [event.target.name]: event.target.value,
    })
    console.log(formData)
  }

  const onSubmit = (data) => {
    // event.preventDefault();
    localStorage.setItem("name", getValues("name"))
    console.log(getValues("name"))
  }
  return (
    <>
      <Head>
        <title>Create Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="backgroudiamge--avatar h-[100vh]">
        <div className="hidden w-full h-[100vh] md:block">
          <div className="border-none">
            <img className="h-[55%]  border-none presbackmg--avatar  fixed !bottom-0 min-w-[100%] " />
          </div>
        </div>
        <div className=" hidden w-[100%] absolute top-[40px] md:flex md:justify-center  md:items-center mx-auto gap-4">
          <img src="Images/MaskGroup57 1 (1).svg" />
          <h4 className="Title--text md:text-[black]">ontheMoons</h4>
        </div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="w-[100%]">
            <div className="flex items-center justify-center">
              <img
                className="hidden absolute top-[13%] md:block"
                src="Images/pngwing (1).svg"
              />
            </div>
            <div className="relative flex">
              <img className=" h-[100vh]" src="Images/Frame10.png" alt="" />
              <img
                className="absolute w-[60%]  xl:hidden right-0 bottom-0"
                src="Images/pngwing.png"
                alt=""
              />
            </div>
            {rpmFrame && (
              <RpmFrame
                setRpmFrame={setRpmFrame}
                userName={getValues("name")}
              />
            )}
            <div className="absolute  xl:w-[80%] md:z-20 md:bottom-0 md:w-[100%] md:px-1 w-[40%] centered pl-24 top-0">
              <div className=" loginscreen--height md:w-[100%] md:px-9 md:absolute md:bottom-[20px] md:flex md:flex-col ">
                <div className="flex md:hidden items-center gap-4">
                  <img src="Images/MaskGroup57 1.svg" />
                  <h4 className="Title--text">ontheMoons</h4>
                </div>

                <h4 className="Subtitle--text md:flex md:h-[120px] md:items-center md:justify-start md:text-start md:text-[20px] md:w-[100%] md:leading-3 w-[80%] md:pt-3 pt-4">
                  Create Avatar{" "}
                  <img
                    src="Images/vecteezy_happy-young-couple-are-hugging-smiling-posing-for-a_11124970_766 1.png"
                    alt=""
                  />
                </h4>

                <div className="bg-white mt-4 md:mt-0 flex items-center w-[77%] rounded-[20px] h-[64px] md:h-[68px] md:rounded-[20px] md:w-[100%] border-2 border-white">
                  <input
                    {...register("name")}
                    type="text"
                    id="name"
                    name="name"
                    placeholder="Name"
                    // value={formData.name}
                    // onChange={handleInputChange}
                    className="w-[100%] md:w-[100%] md:text-[20px] md:h-[68px] md:rounded-[10px] pl-4 createusername--text outline-none rounded-[20px] h-[70px]"
                    defaultValue={"Jhone Doe"}
                  />
                </div>
                <div className="flex items-center justify-between md:w-[100%] md:pt-4 pt-4 w-[77%]">
                  <div className="flex items-center md:gap-3 gap-4">
                    <img src="Images/Rectangle 18.png" alt="" />
                    <img src="Images/Rectangle 19.png" alt="" />
                    <img src="Images/Rectangle 20.png" alt="" />
                    <img src="Images/Rectangle 21.png" alt="" />
                  </div>
                </div>
                {/* <Link href="/avatar-upload"> */}

                <button
                  onClick={() => setRpmFrame(true)}
                  className="bg-white justify-center md:h-[68px] mt-4 flex items-center md:w-[100%] w-[77%] cursor-pointer rounded-[20px]  h-[64px] md:rounded-[20px] md:mt-4 border-2 gap-5 border-white"
                >
                  <h4 className="Button--text md:text-[20px]">
                    Create my avatar
                  </h4>
                  <img className="md:w-[14%]" src="Images/image 8.png" />
                </button>
                <p className="paragraph--text md:hidden loginscreen--text  md:text-[16px] md:pt-5 md:leading-[24px] text-center md:text-center pt-3 w-[73%] md:w-[100%]">
                  By clicking Create, I state that I have read and understood
                  the terms and conditions.
                </p>
                {/* </Link> */}

                <div className="md:flex md:items-center md:justify-center md:flex-col">
                  <div className="flex items-center md:pt-3  pr-[130px] md:pr-0 pt-4 justify-center">
                    <svg
                      width="86"
                      height="10"
                      viewBox="0 0 86 10"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <ellipse
                        cx="4.94795"
                        cy="4.78172"
                        rx="4.67134"
                        ry="4.6411"
                        fill="white"
                      />
                      <ellipse
                        cx="24.0051"
                        cy="4.78172"
                        rx="4.67134"
                        ry="4.6411"
                        fill="white"
                      />
                      <ellipse
                        cx="43.0623"
                        cy="4.78172"
                        rx="4.67134"
                        ry="4.6411"
                        fill="white"
                      />
                      <ellipse
                        cx="62.1196"
                        cy="4.78172"
                        rx="4.67134"
                        ry="4.6411"
                        fill="#AAAAAA"
                      />
                      <ellipse
                        cx="81.0522"
                        cy="4.78172"
                        rx="4.67134"
                        ry="4.6411"
                        fill="#AAAAAA"
                      />
                    </svg>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
      </main>
    </>
  )
}
