import React, { useState, useEffect } from "react"
import Head from "next/head"
import Link from "next/link"
import { Canvas } from "@react-three/fiber"
import ModelAvatar from "@/src/components/ModelAvatar"
import Image from "next/image"

export default function Avator() {
  const [avatarImage, setAvatarImage] = useState()
  useEffect(() => {
    setAvatarImage(
      localStorage.getItem("avatarUrl").split(".glb")[0] + ".png" ??
        "https://models.readyplayer.me/63e0441f5dd77ccae17996bf.png"
    )
  }, [])
  return (
    <>
      <Head>
        <title>Create Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="backgroudiamge--avatar--upload h-[100vh]">
        <div className="hidden w-full h-[100vh] md:block">
          {/* <img className="" src="Images/image 1  (2).svg" /> */}

          <div className="border-none">
            <img className="border-none presbackmg--avatar--upload  fixed !bottom-0 min-w-[100%] " />
          </div>
        </div>
        <div className=" hidden w-[100%] absolute top-[40px] md:flex md:justify-center  md:items-center mx-auto gap-4">
          <img src="Images/MaskGroup57 1 (1).svg" />
          <h4 className="Title--text md:text-[black]">ontheMoons</h4>
        </div>
        <div className="w-[100%]">
          <div className="flex items-center justify-center">
            <img
              className="hidden absolute top-[13%] md:block"
              src="Images/Group 67 (1).svg"
            />
          </div>
          <div className="relative  flex">
            <img className=" h-[100vh]" src="Images/Background.png" alt="" />
            <img
              className="absolute w-[40%] flex items-center justify-center  xl:hidden right-24 bottom-0"
              src="Images/Group 67.png"
              alt=""
            />
          </div>
          <div className="absolute xl:w-[80%]  md:z-50 md:bottom-0 md:w-[100%] md:px-0 w-[40%] centered  pl-24 top-0">
            <div className="upload--avatar md:w-[100%] md:px-9 md:absolute md:bottom-[20px] md:flex md:flex-col ">
              <div className="flex md:hidden items-center gap-4">
                <img src="Images/MaskGroup57 1.svg" />
                <h4 className="Title--text">ontheMoons</h4>
              </div>
              <h4 className="Subtitle--text md:flex md:h-[45px]   md:text-[36px] md:w-[100%] md:leading-3 w-[80%] md:pt-2 pt-6">
                Picture Upload
              </h4>
              <p className="paragraph--text md:text-[16px] md:pt-2 md:leading-[24px]  pt-6 w-[88%] md:w-[100%] md:items-start md:text-start">
                We will take only one original picture but we didn't use that
                picture anywhere to show your identity.{" "}
              </p>

              <div className="flex items-center md:w-[90%] md:pt-0 pt-5 w-[77%]">
                <div className="">
                  {/* <ModelAvatar /> */}
                  {/* <Image
                    className="md:w-[100px] md:h-[80px] w-[183px] h-[188px] bg-slate-200 rounded-lg "
                    width="100%"
                    height="100%"
                    src={avatarImage}
                    alt=""
                  /> */}
                  <img
                    className="md:w-[183px] md:h-[146px] "
                    src="Images/Rectangle 19 (1).png"
                    alt=""
                  />
                </div>
                <img
                  className="md:w-[183px] md:h-[146px] "
                  src="Images/Rectangle 19 (1).png"
                  alt=""
                />
                <div className="bg-white cursor-pointer md:w-[75px] w-[80px] h-[58px] flex items-center justify-center rounded-[14px] baxshadow">
                  <svg
                    width="46"
                    height="47"
                    viewBox="0 0 46 47"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M11.5 23.688H34.5"
                      stroke="black"
                      stroke-width="3"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                    <path
                      d="M23 35.188L23 12.188"
                      stroke="black"
                      stroke-width="3"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    />
                  </svg>
                </div>
              </div>

              <Link href="/home">
                <button className="bg-white justify-center md:h-[60px] mt-8 flex items-center md:w-[100%] w-[77%] cursor-pointer rounded-[20px] h-[64px] md:rounded-[10px] md:mt-0 border-2 gap-5 border-white">
                  <h4 className="Button--text">Next</h4>
                  <img className="md:w-[14%]" src="Images/image 8 (1).svg" />
                </button>
              </Link>

              <div className="md:flex md:items-center md:justify-center md:flex-col">
                <div className="flex items-center md:pt-3  pr-[130px] md:pr-2 pt-4 justify-center">
                  <svg
                    width="86"
                    height="10"
                    viewBox="0 0 86 10"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <ellipse
                      cx="4.94795"
                      cy="4.78172"
                      rx="4.67134"
                      ry="4.6411"
                      fill="white"
                    />
                    <ellipse
                      cx="24.0051"
                      cy="4.78172"
                      rx="4.67134"
                      ry="4.6411"
                      fill="white"
                    />
                    <ellipse
                      cx="43.0623"
                      cy="4.78172"
                      rx="4.67134"
                      ry="4.6411"
                      fill="white"
                    />
                    <ellipse
                      cx="62.1196"
                      cy="4.78172"
                      rx="4.67134"
                      ry="4.6411"
                      fill="white"
                    />
                    <ellipse
                      cx="81.0522"
                      cy="4.78172"
                      rx="4.67134"
                      ry="4.6411"
                      fill="#AAAAAA"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
